services:
  - type: web
    name: ecoshop-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecoshop_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DOMAIN
        value: onrender.com
      - key: FRONTEND_DOMAIN
        value: your-frontend-domain.com
      - key: BASE_URL
        value: https://ecoshop-backend.onrender.com
    healthCheckPath: /api/subdomain/test/ 